README.md
Also add `ca_file` example
This really confused me till I dug into the source.
=> Fix example for truststore to use correct option.

lib/manticore/client.rb
Otherwise the ConnectionManager will be shut down only when the JVM runs finalizers.
=> Explicitly shut down connection manager at exit.

lib/faraday/adapter/manticore.rb
We recently had some issues where our sockets were timing out far quicker than expected.
Manticore (HttpClient) supports 3 timeouts:
* **connectTimeout** - timeout during connection establishment (e.g. TCP handshake)
* **socketTimeout** - idle connection timeout
* **connectionRequestTimeout** - timeout retrieving a connection from the pooled connection manager
Faraday has 2 timeouts:
* **open_timeout** - intended to be the connection establishment timeout
* **timeout** - intended to be the idle connection timeout
The Faraday adapter in Manticore is assigning the Faraday `:timeout` to all 3 of its timeouts, if present. This is reasonable.
However, it would then assign the `:open_timeout` to both the `:socket_timeout` and  `:connect_timeout`. This is broken.
For example, a connection …
=> Stop using Faraday open_timeout as socket_timeout

README.md
Gemfile without platform will not work on latest versions of bundler.
=> Added platform for bundler

CHANGELOG.md
This PR edits the top of the changelog to not confuse the reader about whether 0.6.1 is released. It is no longer "pending".
=> CHANGELOG: drop "pending" about 0.6.1 [ci skip]

.travis.yml
This PR adds JRuby 9.1.8.0 to the build matrix in CI.
=> Travis: Include latest stable release of JRuby

.travis.yml
This PR updates the CI matrix to use latest JRuby.
http://jruby.org/2018/05/24/jruby-9-2-0-0.html
=> Travis: Use JRuby 9.2.0.0

.travis.yml
The build failed like:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jruby/Main : Unsupported major.minor version 52.0
at java.lang.ClassLoader.findBootstrapClass(Native Method)
at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1073)
at java.lang.ClassLoader.loadClass(ClassLoader.java:414)
at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```
https://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-versi
The proposed fix is to **only offer Java 8 to JRuby 9.2.0.0**.
Result: This …
=> Travis: jruby-9.2.0.0 runs on Java 8

ext/manticore/org/manticore/Manticore.java
stumbled upon this while reviewing internal on GH
=> [jruby] less byte[] copy - proper string sharing

.travis.yml
This PR updates the CI matrix to use latest JRuby, 9.2.5.0.
[JRuby 9.2.5.0 release blog post](https://www.jruby.org/2018/12/06/jruby-9-2-5-0.html)
=> Travis: Use jruby-9.2.5.0

.travis.yml, manticore.gemspec
This PR updates the CI matrix to use latest JRuby, **9.2.7.0**.
[JRuby 9.2.7.0 release blog post](https://www.jruby.org/2019/04/09/jruby-9-2-7-0.html)
- Also: Allow Bundler 2 in the gemspec
- Use Bundler 1.17.3 in the CI builds, to suit all versions
=> CI: Use jruby-9.2.7.0, loosen Bundler dependency

README.md
This PR tries to improve on the readability of the examples in the README, by breaking up lines.
=> README: Long lines of examples shorter

lib/manticore.rb, lib/manticore/client.rb
reviewed a few package imports to be explicit about the classes used, 
most interesting is the `org.apache.http.conn.ssl` - [as seen previously](https://github.com/cheald/manticore/issues/87) - there are issues with the dependencies of `org.apache.http.conn.ssl.SSLConnectionSocketFactory` which lead to a `NameError` (not being able to load the class on some JDK setups).
with `include_package` such `NameError` gets lost as it is assumed to be caused by a Java `ClassNotFoundException` but that isn't necessarily always the case. 
by explicitly importing the SSL classes used by manticore's client we should exhibit these failures early (at .rb load time).
=> Refactor: import Java class(es) from package directly

lib/manticore/client.rb
When creating a truststore from a certificate bundle it may happen that two certificates will have the same getSubjectX500Principal, causing the first one to be replaced.
=> don't override certificates with same Subject

lib/manticore.rb, lib/manticore/response.rb, manticore.gemspec, spec/manticore/client_spec.rb, spec/manticore/response_spec.rb
It's very annoying to rescue `ManticoreException` and have a `nil` cause despite these being caused by Java exceptions.
Since Ruby can not fill the `cause` for us (due the way the mapping logic is laid out) let's set the cause manually.
=> [feat] set Java cause for ManticoreException types

lib/manticore/client.rb
There is an [issue](https://issues.apache.org/jira/browse/HTTPCLIENT-1478?focusedCommentId=15998229&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15998229) in apache HTTP client that cause SSL handshake hangs indefinitely.
The issue happens only with proxy server. The socket timeout is unset in the handshake phase.
This commit set the default socket config to PoolingHttpClientConnectionManager explicitly, so the timeout is non zero
Related issue: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1033
=> Fix SSL handshake hang indefinitely

Rakefile, lib/manticore/client.rb, spec/manticore/client_spec.rb, spec/spec_helper.rb
`TrustSelfSignedStrategy` only allows self-signed certificates by
checking that the chain length is 1. This doesn't work for certificates
that are signed by an untrusted CA. Newer versions of httpclient (>=
4.5.4) provide `TrustAllStrategy`, which returns true for all
certificate chains. That won't be available until
https://github.com/cheald/manticore/pull/99 is merged, so this copies
the implementation and uses it when SSL verification is disabled.
=> Accept untrusted certs when SSL verify is disabled

lib/manticore/client.rb, spec/manticore/client_spec.rb
`verify: :disabled` still disables all verification as expected, 
the (deprecated) `verify: false` stays as in < **0.8** (before #100)
=> [feat] restore compat with (legacy) verify: false

README.md
The previous badge was for a stopped build system.
=> docs: Use correct build status badge in README

lib/manticore.rb, lib/manticore/client.rb, lib/manticore/client/trust_strategies.rb, spec/manticore/client_spec.rb, spec/manticore/client_trust_strategies_spec.rb
Adds an advanced feature so consumers of this library can provide their own
TrustStrategy to refine the situations where the TrustManager can be bypassed.
Consumers can pass either native java implementations of TrustStrategy, or a
ruby-defined Proc that is expected to handle ruby-OpenSSL X509 Certificates.
Works with the trust_strategy that is possibly instantiated with some
values of `ssl[:verify]` to produce a _combined_ TrustStrategy that will
bypass the TrustManager if _any_ of the configured trust strategies indicate
that the cert chain qualifies for a bypass.
=> ssl[:trust_strategy]: wrapper for org.apache.http.conn.ssl.TrustStrategy

Rakefile, lib/manticore/client.rb, spec/manticore/client_spec.rb
Strip removes all whitespace characters, not just line breaks and spaces (null, horizontal tab, line feed, vertical tab, form feed, carriage return, space). If a certificate ends with such a character, a Java::JavaSecuritySpec::InvalidKeySpecException is thrown. For example, this [issue](https://github.com/logstash-plugins/logstash-output-http/issues/92) results from this bug.
=> Don't strip the decoded certificate, chomp should be enough

lib/manticore.rb, lib/manticore/client.rb, spec/manticore/client_spec.rb
Currently if we use  illegal characters in uri example `https://www.google.com?q=baz{{||  ` which fails with java.net.URISyntaxException. This pr provided wrapper around java exception to handle uri syntax exception.
=> Raises InvalidUriException for java URISyntaxException

lib/manticore/client.rb, spec/manticore/client_spec.rb
Currently a non-body get/delete will sent a "Content-Length: 0" header given the httpclient is passed a request object with Entity.
While RFC 7230 does allow for non-body requests to have "Content-Length: 0" it is marked as a SHOULD NOT and can cause problems in stricter environments.
This commit changes that, where a no body request will use non-entity objects.
fixes https://github.com/logstash-plugins/logstash-input-http_poller/issues/150
=> don't send entity when get/delete have no body
